name: Saludo usando variables

on:
  workflow_dispatch

env:
  DIA_DE_SEMANA: Lunes

jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        env:
          EMOJI: ":smile:"
        run: echo "$SALUDO, ${{ vars.MI_VARIABLE }}. Hoy es $DIA_DE_SEMANA! $EMOJI"
        